steps:
# Build image Docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/braille-app:$COMMIT_SHA', '.']
# Push image ke Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/braille-app:$COMMIT_SHA']
# Deploy ke Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'my-app'
  - '--image'
  - 'gcr.io/$PROJECT_ID/braille-app:$COMMIT_SHA'
  - '--region'
  - 'asia-southeast2'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated' 
  - '--set-secrets'
  - 'gcp-credentials=gcp-credentials:latest'

# Opsi tambahan (opsional)
options:
  region: asia-southeast2
  logging: CLOUD_LOGGING_ONLY
timeout: '1200s'