steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Ekspor secret credentials.json ke variabel
      echo $$(gcloud secrets versions access latest --secret=gcp-credentials) > credential.json

      # Install dependencies
      pip install -r requirements.txt

      # Jalankan aplikasi untuk testing
      python app.py

# Deploy aplikasi ke Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - run
    - deploy
    - my-app
    - --source=.
    - --platform=managed
    - --region=asia-southeast2
    - --allow-unauthenticated
    - --update-env-vars=GOOGLE_APPLICATION_CREDENTIALS=credential.json

options:
  region: us-central1
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
