steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/modelapi', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/modelapi']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - run
    - deploy
    - modelapi
    - --image=gcr.io/$PROJECT_ID/modelapi
    - --platform=managed
    - --region=us-central1
    - --allow-unauthenticated
    - --set-secrets=credential.json=gcp-credentials:latest
