# Gunakan base image Python
FROM python:3.9-slim

# Set direktori kerja di dalam container
WORKDIR /app

# Salin file requirements.txt ke dalam container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file ke dalam container, kecuali yang ada di .gitignore
COPY . .

# Expose port Flask (opsional, jika menggunakan default Flask port)
EXPOSE 5000

# Menjalankan aplikasi Flask
CMD ["python", "app.py"]
