# Gunakan base image Python
FROM python:3.9-slim

# Set lingkungan kerja di container
WORKDIR /app

# Salin file requirements.txt ke dalam container
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file aplikasi ke dalam container
COPY . .

# Set entry point untuk aplikasi Flask
CMD ["python", "app.py"]
